"""Add cancellation tracking tables and fields

Revision ID: d3872ba21745
Revises: ff701cb6b558
Create Date: 2026-02-01 12:20:52.206692+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3872ba21745'
down_revision: Union[str, None] = 'ff701cb6b558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_reason',
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_inspection', sa.Boolean(), nullable=False),
    sa.Column('auto_restock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('reason_id')
    )
    op.create_index(op.f('ix_cancellation_reason_reason_code'), 'cancellation_reason', ['reason_code'], unique=True)
    op.create_index(op.f('ix_cancellation_reason_reason_type'), 'cancellation_reason', ['reason_type'], unique=False)
    op.create_table('order_cancellations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_detail_id', sa.Integer(), nullable=True),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('cancellation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelled_quantity', sa.Integer(), nullable=True),
    sa.Column('restock_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restocked_at', sa.DateTime(), nullable=True),
    sa.Column('restocked_quantity', sa.Integer(), nullable=True),
    sa.Column('platform_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform_refund_amount', sa.Float(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['order_detail_id'], ['order_details.detail_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['cancellation_reason.reason_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_cancellations_cancellation_type'), 'order_cancellations', ['cancellation_type'], unique=False)
    op.create_index(op.f('ix_order_cancellations_cancelled_at'), 'order_cancellations', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_order_cancellations_cancelled_by_user_id'), 'order_cancellations', ['cancelled_by_user_id'], unique=False)
    op.create_index(op.f('ix_order_cancellations_order_detail_id'), 'order_cancellations', ['order_detail_id'], unique=False)
    op.create_index(op.f('ix_order_cancellations_order_id'), 'order_cancellations', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_cancellations_platform_reference'), 'order_cancellations', ['platform_reference'], unique=False)
    op.create_index(op.f('ix_order_cancellations_reason_id'), 'order_cancellations', ['reason_id'], unique=False)
    op.create_index(op.f('ix_order_cancellations_restock_status'), 'order_cancellations', ['restock_status'], unique=False)
    op.alter_column('audit_log', 'action_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('order_details', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.add_column('order_details', sa.Column('cancelled_quantity', sa.Integer(), nullable=False))
    op.add_column('order_details', sa.Column('cancellation_reason_id', sa.Integer(), nullable=True))
    op.add_column('order_details', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('order_details', sa.Column('return_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order_details', sa.Column('returned_quantity', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_details_cancellation_reason_id'), 'order_details', ['cancellation_reason_id'], unique=False)
    op.create_index(op.f('ix_order_details_is_cancelled'), 'order_details', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_order_details_return_status'), 'order_details', ['return_status'], unique=False)
    op.create_foreign_key(None, 'order_details', 'cancellation_reason', ['cancellation_reason_id'], ['reason_id'])
    op.add_column('orders', sa.Column('cancellation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_cancellation_status'), 'orders', ['cancellation_status'], unique=False)
    op.create_index(op.f('ix_orders_cancelled_at'), 'orders', ['cancelled_at'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['cancelled_by_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_cancelled_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_cancellation_status'), table_name='orders')
    op.drop_column('orders', 'cancelled_by_user_id')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancellation_status')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_index(op.f('ix_order_details_return_status'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_is_cancelled'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_cancellation_reason_id'), table_name='order_details')
    op.drop_column('order_details', 'returned_quantity')
    op.drop_column('order_details', 'return_status')
    op.drop_column('order_details', 'cancelled_at')
    op.drop_column('order_details', 'cancellation_reason_id')
    op.drop_column('order_details', 'cancelled_quantity')
    op.drop_column('order_details', 'is_cancelled')
    op.alter_column('audit_log', 'action_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_order_cancellations_restock_status'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_reason_id'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_platform_reference'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_order_id'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_order_detail_id'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_cancelled_by_user_id'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_cancelled_at'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_cancellation_type'), table_name='order_cancellations')
    op.drop_table('order_cancellations')
    op.drop_index(op.f('ix_cancellation_reason_reason_type'), table_name='cancellation_reason')
    op.drop_index(op.f('ix_cancellation_reason_reason_code'), table_name='cancellation_reason')
    op.drop_table('cancellation_reason')
    # ### end Alembic commands ###
