"""Remove tracking, add action_type, update audit_log and driver_teams

Revision ID: ff701cb6b558
Revises: 1f87f4c199ba
Create Date: 2026-01-31 07:53:23.604378+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff701cb6b558'
down_revision: Union[str, None] = '1f87f4c199ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. First drop the FK constraint on items before dropping tracking table
    op.drop_constraint('items_tracking_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'tracking_id')
    
    # 2. Now we can safely drop the tracking table
    op.drop_index('ix_tracking_tracking_name', table_name='tracking')
    op.drop_table('tracking')
    
    # 3. Update audit_log to use action_id FK instead of action VARCHAR
    op.add_column('audit_log', sa.Column('action_id', sa.Integer(), nullable=True))
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_column('audit_log', 'action')
    op.create_index(op.f('ix_audit_log_action_id'), 'audit_log', ['action_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'action_type', ['action_id'], ['action_id'])
    
    # 4. Add user_id to driver_teams
    op.add_column('driver_teams', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_driver_teams_user_id'), 'driver_teams', ['user_id'], unique=False)
    op.create_foreign_key(None, 'driver_teams', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tracking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_tracking_id_fkey', 'items', 'tracking', ['tracking_id'], ['tracking_id'])
    op.drop_constraint(None, 'driver_teams', type_='foreignkey')
    op.drop_index(op.f('ix_driver_teams_user_id'), table_name='driver_teams')
    op.drop_column('driver_teams', 'user_id')
    op.add_column('audit_log', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_action_id'), table_name='audit_log')
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.drop_column('audit_log', 'action_id')
    op.create_table('tracking',
    sa.Column('tracking_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tracking_id', name='tracking_pkey')
    )
    op.create_index('ix_tracking_tracking_name', 'tracking', ['tracking_name'], unique=True)
    # ### end Alembic commands ###
